# Generated by Django 6.0.4 on 2026-05-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('modelregistry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRunRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zenml_run_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('base_model_stac_id', models.CharField(max_length=200)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('status_cache', models.CharField(default='initializing', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='datasets.dataset')),
                ('local_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='modelregistry.localmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['local_model'], name='trainings_t_local_m_b5fe29_idx'), models.Index(fields=['status_cache'], name='trainings_t_status__77d437_idx'), models.Index(fields=['user'], name='trainings_t_user_id_766d81_idx'), models.Index(fields=['base_model_stac_id'], name='trainings_t_base_mo_5deec9_idx')],
            },
        ),
    ]
