# Generated by Django 6.0.4 on 2026-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrunref',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
