# Generated by Django 6.0.4 on 2026-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_trainingrunref_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrunref',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
