# Generated by Django 6.0.4 on 2026-05-05 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_remove_dataset_build_error'),
        ('modelregistry', '0002_rename_stac_id_localmodel_name'),
        ('trainings', '0003_trainingrunref_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingrunref',
            name='trainings_t_status__77d437_idx',
        ),
        migrations.RenameField(
            model_name='trainingrunref',
            old_name='status_cache',
            new_name='status',
        ),
        migrations.AddIndex(
            model_name='trainingrunref',
            index=models.Index(fields=['status'], name='trainings_t_status_b49eb0_idx'),
        ),
    ]
