# Generated by Django 6.0.4 on 2026-07-22 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0004_dataset_dataset_status_valid_and_more'),
        ('modelregistry', '0004_localmodel_localmodel_status_valid_and_more'),
        ('trainings', '0004_remove_trainingrunref_trainings_t_status__77d437_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrunref',
            name='status',
            field=models.CharField(choices=[('initializing', 'Initializing'), ('submitted', 'Submitted'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cached', 'Cached'), ('retrying', 'Retrying'), ('retried', 'Retried'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='initializing', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='trainingrunref',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['initializing', 'submitted', 'provisioning', 'running', 'completed', 'failed', 'cached', 'retrying', 'retried', 'stopping', 'stopped'])), name='trainingrunref_status_valid'),
        ),
    ]
