apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fair.backend.fullname" . }}
  labels:
    {{- include "fair.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- if not .Values.postgres.enabled }}
  DATABASE_HOST: {{ .Values.externalDatabase.host | quote }}
  DATABASE_PORT: {{ .Values.externalDatabase.port | toString | quote }}
  DATABASE_NAME: {{ .Values.externalDatabase.database | quote }}
  DATABASE_USER: {{ .Values.externalDatabase.username | quote }}
  {{- end }}
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
