{{- if and (not .Values.postgres.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fair.backend.fullname" . }}-db
  labels:
    {{- include "fair.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    {{- include "fair.syncWave" "-10" | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
