export enum PmtilesConversionStatus {
  SUBMITTED = "SUBMITTED",
  FINISHED = "FINISHED",
}

export enum MapSwipeProcessingStatus {
  READY_TO_PROCESS = "READY_TO_PROCESS",
  DISCARDED = "DISCARDED",
  PROCESSING_FAILED = "PROCESSING_FAILED",
  PUBLISHING_FAILED = "PUBLISHING_FAILED",
  WITHDRAWN = "WITHDRAWN",
  PROCESSED = "PROCESSED",
  PUBLISHED = "PUBLISHED",
  FINISHED = "FINISHED",
  PAUSED = "PAUSED",
  READY_TO_PUBLISH = "READY_TO_PUBLISH",
  DRAFT = "DRAFT",
}
