# Generated by Django 6.0.4 on 2026-05-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localmodel',
            old_name='stac_id',
            new_name='name',
        ),
    ]
