# Generated by Django 6.0.4 on 2026-07-22 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0003_localmodel_visibility_alter_localmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='localmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='localmodel_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='localmodel',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['private', 'public'])), name='localmodel_visibility_valid'),
        ),
    ]
