# Generated by Django 6.0.4 on 2026-07-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0004_localmodel_localmodel_status_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('buildings', 'Buildings'), ('solar-panels', 'Solar Panels'), ('trees', 'Trees'), ('roads', 'Roads'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('status', models.CharField(choices=[('registering', 'Registering'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='registering', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='public', max_length=20)),
                ('stac_item', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_models', to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='modelregist_status_f2a598_idx'), models.Index(fields=['user'], name='modelregist_user_id_b604eb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['registering', 'active', 'failed', 'archived'])), name='basemodel_status_valid'), models.CheckConstraint(condition=models.Q(('visibility__in', ['private', 'public'])), name='basemodel_visibility_valid')],
            },
        ),
    ]
