# Generated by Django 6.0.4 on 2026-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0005_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='stac_item_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='localmodel',
            name='category',
            field=models.CharField(choices=[('buildings', 'Buildings'), ('solar-panels', 'Solar Panels'), ('trees', 'Trees'), ('roads', 'Roads'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
    ]
