# Generated by Django 6.0.4 on 2026-07-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0006_basemodel_stac_item_url_localmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='stac_item_url',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='stac_item_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='localmodel',
            name='stac_item_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
