# Generated by Django 6.0.4 on 2026-07-29 19:43

import django.db.models.deletion
from django.db import migrations, models

_SEED = [
    ("buildings", "Buildings"),
    ("solar-panels", "Solar Panels"),
    ("trees", "Trees"),
    ("roads", "Roads"),
    ("other", "Other"),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("modelregistry", "Category")
    for slug, label in _SEED:
        Category.objects.get_or_create(slug=slug, defaults={"label": label})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("modelregistry", "Category")
    Category.objects.filter(slug__in=[s for s, _ in _SEED]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0007_remove_basemodel_stac_item_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['slug'],
            },
        ),
        migrations.RunPython(seed_categories, unseed_categories),
        migrations.AlterField(
            model_name='basemodel',
            name='category',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.PROTECT, related_name='base_models', to='modelregistry.category', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='localmodel',
            name='category',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.PROTECT, related_name='local_models', to='modelregistry.category', to_field='slug'),
        ),
    ]
