# Generated by Django 6.0.4 on 2026-07-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0009_localmodel_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='localmodel',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
