# Generated by Django 6.0.4 on 2026-07-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelregistry', '0010_basemodel_is_pinned_localmodel_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='stac_item',
        ),
    ]
