FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.8.0 --activate

COPY package.json pnpm-lock.yaml ./

RUN echo "Installing dependencies..." && \
    pnpm install --frozen-lockfile 

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]