## docker build -t fair-frontend:latest -f Dockerfile.prod . && container_id=$(docker create fair-frontend:latest) && docker cp $container_id:/app/dist ./dist && docker rm $container_id


# Build stage
FROM node:22 AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
# COPY .env ./.env
RUN npm install -g pnpm@9.8.0
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

# Export stage
FROM alpine:latest AS exporter
WORKDIR /app
COPY --from=builder /app/dist ./dist
