# Generated by Django 4.1.4 on 2025-04-02 13:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmuser',
            name='account_deletion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osmuser',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osmuser',
            name='notifications_delivery_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Email'), ('web', 'Web')], max_length=10), blank=True, default=['web'], size=None),
        ),
    ]
