# Generated by Django 4.1.4 on 2025-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_osmuser_account_deletion_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
