# fAIr Application Development Stack

x-common-env: &common-env
  env_file:
    - ${ENV_FILE:-.env.dev}

services:
  postgres:
    <<: *common-env
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    volumes:
      - ${POSTGRES_DATA:-./fair-app/data/postgres}:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    <<: *common-env
    image: redis:8-alpine
    platform: linux/amd64
    container_name: redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - ${REDIS_DATA:-./fair-app/data/redis}:/data
    ports:
      - "6379:6379"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-api:
    <<: *common-env
    image: ghcr.io/hotosm/fair-api:develop
    build:
      context: ./backend
      dockerfile: Dockerfile.API
    platform: linux/amd64
    container_name: api
    restart: unless-stopped
    command: python manage.py runserver_with_q 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ${APP_LOGS:-./fair-app/data/log}:/app/log
      - ${RAMP_HOME:-./fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./fair-app/data/trainings}:/TRAINING_WORKSPACE
      - ${APP_HOME:-./}backend/core:/app/core
      - ${APP_HOME:-./}backend/login:/app/login
      - ${APP_HOME:-./}backend/aiproject:/app/aiproject
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import sys, requests; r = requests.get(''http://127.0.0.1:8000/api/''); print(r); sys.exit(0 if r.status_code==200 else 1)"',
        ]
      interval: 30s
      timeout: 10s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  backend-worker-cpu:
    <<: *common-env
    profiles: ["cpu"]
    image: ghcr.io/hotosm/fair-worker:develop-cpu
    build:
      context: ./backend
      dockerfile: Dockerfile.workers
      args:
        - BUILD_TYPE=cpu
    platform: linux/amd64
    container_name: worker-cpu
    restart: unless-stopped
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training
    volumes:
      - ${APP_LOGS:-./fair-app/data/log}:/app/log
      - ${RAMP_HOME:-./fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./fair-app/data/trainings}:/TRAINING_WORKSPACE
      - ${APP_HOME:-./}backend/core:/app/core
      - ${APP_HOME:-./}backend/login:/app/login
      - ${APP_HOME:-./}backend/aiproject:/app/aiproject
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  backend-worker-gpu:
    <<: *common-env
    profiles: ["gpu"]
    image: ghcr.io/hotosm/fair-worker:develop-gpu
    build:
      context: ./backend
      dockerfile: Dockerfile.workers
      args:
        - BUILD_TYPE=gpu
    platform: linux/amd64
    container_name: worker-gpu
    restart: unless-stopped
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training --pool=solo
    volumes:
      - ${APP_LOGS:-./fair-app/data/log}:/app/log
      - ${RAMP_HOME:-./fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./fair-app/data/trainings}:/TRAINING_WORKSPACE
      - ${APP_HOME:-./}backend/core:/app/core
      - ${APP_HOME:-./}backend/login:/app/login
      - ${APP_HOME:-./}backend/aiproject:/app/aiproject
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
        limits:
          memory: 4G

  prediction-worker:
    <<: *common-env
    image: ghcr.io/hotosm/fair-offline-predictor:develop
    build:
      context: ./backend
      dockerfile: Dockerfile.API
      args:
        - BUILD_TARGET=predictor
    platform: linux/amd64
    container_name: prediction-worker
    restart: unless-stopped
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q predictions --pool=solo
    volumes:
      - ${APP_LOGS:-./fair-app/data/log}:/app/log
      - ${RAMP_HOME:-./fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./fair-app/data/trainings}:/TRAINING_WORKSPACE
      - ${APP_HOME:-./}backend/core:/app/core
      - ${APP_HOME:-./}backend/login:/app/login
      - ${APP_HOME:-./}backend/aiproject:/app/aiproject
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  flower:
    <<: *common-env
    image: mher/flower:2.0.1
    platform: linux/amd64
    container_name: flower
    restart: unless-stopped
    command: celery --broker=redis://${REDIS_USER:-redis}:${REDIS_PASSWORD:-}@redis:6379/0 flower --address=0.0.0.0 --port=5000
    ports:
      - "5500:5000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
    profiles:
      - cpu
      - gpu

networks:
  backend-network:
    driver: bridge
