x-common-env: &common-env
  env_file:
    - ${ENV_FILE:-.env.production}

services:
  postgres:
    <<: *common-env
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA:-/opt/fair-app/data/postgres}:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    <<: *common-env
    image: redis:8-alpine
    platform: linux/amd64
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-/opt/fair-app/data/redis}:/data
    ports:
      - "127.0.0.1:6378:6379"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-api:
    <<: *common-env
    image: ghcr.io/hotosm/fair-api:${TAG:-latest}
    platform: linux/amd64
    container_name: api
    restart: always
    command: python manage.py runserver_with_q 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ${APP_LOGS:-/opt/fair-app/data/log}:/app/log
      - ${RAMP_HOME:-/opt/fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-/opt/fair-app/data/trainings}:/TRAINING_WORKSPACE
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import sys, requests; r = requests.get(''http://127.0.0.1:8000/api/''); print(r); sys.exit(0 if r.status_code==200 else 1)"',
        ]
      interval: 30s
      timeout: 10s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  backend-worker-cpu:
    <<: *common-env
    profiles: ["cpu"]
    image: ghcr.io/hotosm/fair-worker:${TAG:-latest}-cpu
    platform: linux/amd64
    container_name: worker-cpu
    restart: always
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training
    volumes:
      - ${APP_LOGS:-/opt/fair-app/data/log}:/app/log
      - ${RAMP_HOME:-/opt/fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-/opt/fair-app/data/trainings}:/TRAINING_WORKSPACE
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

  backend-worker-gpu:
    <<: *common-env
    profiles: ["gpu"]
    image: ghcr.io/hotosm/fair-worker:${TAG:-latest}-gpu
    platform: linux/amd64
    container_name: worker-gpu
    restart: always
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training --pool=solo
    volumes:
      - ${APP_LOGS:-/opt/fair-app/data/log}:/app/log
      - ${RAMP_HOME:-/opt/fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-/opt/fair-app/data/trainings}:/TRAINING_WORKSPACE
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G

  prediction-worker:
    <<: *common-env
    image: ghcr.io/hotosm/fair-offline-predictor:${TAG:-latest}
    platform: linux/amd64
    container_name: prediction-worker
    restart: always
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q predictions --pool=solo
    volumes:
      - ${APP_LOGS:-/opt/fair-app/data/log}:/app/log
      - ${RAMP_HOME:-/opt/fair-app/data/ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-/opt/fair-app/data/trainings}:/TRAINING_WORKSPACE
    depends_on:
      backend-api:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

  flower:
    <<: *common-env
    image: mher/flower:2.0.1
    platform: linux/amd64
    container_name: flower
    restart: always
    command: celery --broker=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/0 flower --address=0.0.0.0 --port=5000 --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin}
    ports:
      - "127.0.0.1:5500:5000"
    networks:
      - backend-network
    depends_on:
      backend-api:
        condition: service_healthy
    profiles:
      - cpu
      - gpu

networks:
  backend-network:
    driver: bridge
