services:
  postgres:
    image: postgis/postgis
    platform: linux/amd64
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis
    platform: linux/amd64
    container_name: redis
    ports:
      - "6379:6379"

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.API
    platform: linux/amd64
    container_name: api
    command: python manage.py runserver_with_q 0.0.0.0:8000
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/log:/app/log
      - ./backend/core:/app/core
      - ./backend/login:/app/login
      - ./backend/aiproject:/app/aiproject
      - ${RAMP_HOME:-./ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./trainings}:/TRAINING_WORKSPACE
    depends_on:
      - redis
      - postgres

  backend-worker-cpu:
    profiles: ["cpu"]
    build:
      context: ./backend
      dockerfile: Dockerfile.workers
      args:
        - BUILD_TYPE=cpu
    platform: linux/amd64
    container_name: worker-cpu
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/log:/app/log
      - ./backend/core:/app/core
      - ./backend/login:/app/login
      - ./backend/aiproject:/app/aiproject
      - ${RAMP_HOME:-./ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./trainings}:/TRAINING_WORKSPACE
    depends_on:
      - backend-api
      - redis
      - postgres

  backend-worker-gpu:
    profiles: ["gpu"]
    build:
      context: ./backend
      dockerfile: Dockerfile.workers
      args:
        - BUILD_TYPE=gpu
    platform: linux/amd64
    container_name: worker-gpu
    command: celery -A aiproject worker --loglevel=INFO --concurrency=1 -Q ramp_training,yolo_training
    env_file:
      - ./backend/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./backend/log:/app/log
      - ./backend/core:/app/core
      - ./backend/login:/app/login
      - ./backend/aiproject:/app/aiproject
      - ${RAMP_HOME:-./ramp}:/RAMP_HOME
      - ${TRAINING_WORKSPACE:-./trainings}:/TRAINING_WORKSPACE
    depends_on:
      - backend-api
      - redis
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    container_name: frontend
    command: pnpm run dev --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
