## docker build -t fair-api -f Dockerfile.API . 

## For Development:

## docker run --env-file .env --rm -p 8000:8000 -v $(pwd):/app/code --name fair-api-container fair-api

## in order to access localhost port to your system from docker env you might wanna use : host.docker.internal or ip 
FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim AS builder

ARG BUILD_TARGET=api

# Configure uv settings
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=0

RUN apt-get update && apt-get install -y --no-install-recommends \
    gdal-bin \
    libgdal-dev \
    gcc \
    build-essential \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

WORKDIR /app

COPY pyproject.toml uv.lock manage.py /app/
COPY auth-libs /app/auth-libs

RUN --mount=type=cache,target=/root/.cache/uv \
    echo "Supplied BUILD_TARGET: $BUILD_TARGET" && \
    if [ "$BUILD_TARGET" = "predictor" ]; then \
    uv sync \
    --frozen \
    --no-install-project \
    --no-dev \
    --group prediction-workers; \
    else \
    uv sync \
    --frozen \
    --no-install-project \
    --no-dev; \
    fi

COPY fairproject /app/fairproject
COPY core /app/core
COPY login /app/login


FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    gdal-bin \
    libgdal-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app /app

ENV PATH="/app/.venv/bin:$PATH"

WORKDIR /app

EXPOSE 8080

CMD ["python", "manage.py", "runserver_with_q", "0.0.0.0:8000"]