ARG BUILD_TYPE=cpu

FROM ghcr.io/hotosm/ramp-code-fair:latest-${BUILD_TYPE}  AS builder


RUN pip install --no-cache-dir uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_MANAGED_PYTHON=1

WORKDIR /app

COPY pyproject.toml uv.lock manage.py /app/
RUN uv pip compile --python-version=3.10  pyproject.toml -o requirements.txt --group api --group base-workers --group ramp-workers \
    && pip install --no-cache-dir -r requirements.txt

COPY aiproject /app/aiproject
COPY core /app/core
COPY login /app/login

FROM ghcr.io/hotosm/ramp-code-fair:latest-${BUILD_TYPE} AS final

COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.10/dist-packages
COPY --from=builder /app /app

EXPOSE 8080

CMD ["bash"]