# Use a specific base image with the desired TensorFlow version
FROM tensorflow/tensorflow:2.9.2

# Update package lists and install necessary dependencies in a single step
RUN apt-get update && \
    apt-get install -y software-properties-common python3-opencv && \
    add-apt-repository ppa:ubuntugis/ppa && \
    apt-get update && \
    apt-get install -y gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for GDAL
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# Install specific version of NumPy
RUN pip install numpy==1.23.5

# Install GDAL with specified options
RUN pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==$(gdal-config --version)

# Copy and install Python requirements
COPY docker/ramp/docker-requirements.txt /tmp/docker-requirements.txt
RUN pip install -r /tmp/docker-requirements.txt

# Upgrade setuptools
RUN pip install --upgrade setuptools

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Install solaris and scikit-fmm packages
COPY docker/ramp/solaris /tmp/solaris
RUN pip install /tmp/solaris --use-feature=in-tree-build && \
    pip install scikit-fmm --use-feature=in-tree-build

# Set working directory and copy the application code
WORKDIR /app
COPY . /app

