ARG BASE_IMAGE=ghcr.io/kshitijrajsharma/ramp-code-fair/tensorflow-gpu:latest

# Stage 1: Builder
FROM ${BASE_IMAGE}  AS builder

RUN pip install --no-cache-dir uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_MANAGED_PYTHON=1

WORKDIR /app

COPY pyproject.toml uv.lock manage.py /app/

# Resolve deps and install globally
RUN uv pip compile pyproject.toml -o requirements.txt --group workers \
    && pip install -r requirements.txt

COPY aiproject /app/aiproject
COPY core /app/core
COPY login /app/login


EXPOSE 8080

CMD ["bash"]