# Generated by Django 6.0.4 on 2026-09-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
            options={
                'db_table': 'user_state',
                'ordering': ['-timestamp'],
            },
        ),
    ]
