ARG ZENML_VERSION
FROM ghcr.io/spwoodcock/awscli-kubectl:latest AS cli-tools


FROM ghcr.io/hotosm/zenml-postgres:${ZENML_VERSION} AS cli
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    fish \
    git \
    && rm -rf /var/lib/apt/lists/*
COPY --from=cli-tools /usr/bin/tofu /usr/bin/tofu
COPY --from=cli-tools /usr/bin/kubectl /usr/bin/kubectl
COPY --from=cli-tools /usr/local/aws-cli /usr/local/aws-cli
RUN ln -sf /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws
COPY --from=cli-tools /usr/local/bin/kubeseal /usr/local/bin/kubeseal
COPY --from=cli-tools /usr/local/bin/helm /usr/local/bin/helm
COPY --from=cli-tools /usr/local/bin/kubie /usr/local/bin/kubie
COPY --from=cli-tools /usr/local/bin/kubectl-cnpg /usr/local/bin/kubectl-cnpg
COPY --from=cli-tools /root/.config/fish/config.fish /root/.config/fish/config.fish
COPY --from=cli-tools /root/.config/fish/fish_variables /root/.config/fish/fish_variables
ENV SHELL=/usr/bin/fish
SHELL ["/usr/bin/fish", "-c"]
ENTRYPOINT ["fish", "-c"]
CMD [ "fish"]
