/** Environment variables, preferring runtime config over build config. */

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: Record<string, string | undefined>;
  }
}

const runtime =
  (typeof window !== "undefined" && window.__RUNTIME_CONFIG__) || {};
const env: Record<string, string | undefined> = { ...import.meta.env };
for (const [key, value] of Object.entries(runtime)) {
  if (value) env[key] = value;
}

export const ENVS = {
  BASE_API_URL: env.VITE_BASE_API_URL,

  AUTH_PROVIDER: env.VITE_AUTH_PROVIDER,
  HANKO_URL: env.VITE_HANKO_URL,

  MATOMO_ID: env.VITE_MATOMO_ID,

  MATOMO_APP_DOMAIN: env.VITE_MATOMO_APP_DOMAIN,

  KPI_STATS_CACHE_TIME: env.VITE_KPI_STATS_CACHE_TIME,

  MAX_TRAINING_AREA_SIZE: env.VITE_MAX_TRAINING_AREA_SIZE,

  MIN_TRAINING_AREA_SIZE: env.VITE_MIN_TRAINING_AREA_SIZE,

  MAX_TRAINING_AREA_UPLOAD_FILE_SIZE:
    env.VITE_MAX_TRAINING_AREA_UPLOAD_FILE_SIZE,

  FAIR_VERSION: env.VITE_FAIR_VERSION,

  OSM_HASHTAGS: env.VITE_OSM_HASHTAGS,

  MAX_ZOOM_LEVEL: env.VITE_MAX_ZOOM_LEVEL,

  MIN_ZOOM_LEVEL_FOR_START_MAPPING_PREDICTION:
    env.VITE_MIN_ZOOM_LEVEL_FOR_START_MAPPING_PREDICTION,

  MIN_ZOOM_LEVEL_FOR_TRAINING_AREA_LABELS:
    env.VITE_MIN_ZOOM_LEVEL_FOR_TRAINING_AREA_LABELS,

  TRAINING_AREAS_AOI_FILL_COLOR: env.VITE_TRAINING_AREAS_AOI_FILL_COLOR,

  TRAINING_AREAS_AOI_OUTLINE_COLOR: env.VITE_TRAINING_AREAS_AOI_OUTLINE_COLOR,

  TRAINING_AREAS_AOI_OUTLINE_WIDTH: env.VITE_TRAINING_AREAS_AOI_OUTLINE_WIDTH,

  TRAINING_AREAS_AOI_FILL_OPACITY: env.VITE_TRAINING_AREAS_AOI_FILL_OPACITY,

  TRAINING_AREAS_AOI_LABELS_FILL_OPACITY:
    env.VITE_TRAINING_AREAS_AOI_LABELS_FILL_OPACITY,

  TRAINING_AREAS_AOI_LABELS_OUTLINE_WIDTH:
    env.VITE_TRAINING_AREAS_AOI_LABELS_OUTLINE_WIDTH,

  TRAINING_AREAS_AOI_LABELS_FILL_COLOR:
    env.VITE_TRAINING_AREAS_AOI_LABELS_FILL_COLOR,

  TRAINING_AREAS_MASK_FILL_COLOR: env.VITE_TRAINING_AREAS_MASK_FILL_COLOR,

  TRAINING_AREAS_AOI_LABELS_OUTLINE_COLOR:
    env.VITE_TRAINING_AREAS_AOI_LABELS_OUTLINE_COLOR,

  JOSM_REMOTE_URL: env.VITE_JOSM_REMOTE_URL,

  TRAINING_AREA_LABELS_FETCH_POOLING_INTERVAL_MS:
    env.VITE_TRAINING_AREA_LABELS_FETCH_POOLING_INTERVAL_MS,

  OSM_LAST_UPDATED_POOLING_INTERVAL_MS:
    env.VITE_OSM_LAST_UPDATED_POOLING_INTERVAL_MS,

  MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREA_LABELS:
    env.VITE_MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREA_LABELS,

  MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREAS:
    env.VITE_MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREAS,

  MAX_ACCEPTABLE_POLYGON_IN_TRAINING_AREA_GEOJSON_FILE:
    env.VITE_MAX_ACCEPTABLE_POLYGON_IN_TRAINING_AREA_GEOJSON_FILE,

  FAIR_PREDICTOR_API_URL: env.VITE_FAIR_PREDICTOR_API_URL,

  OSM_DATABASE_STATUS_API_URL: env.VITE_OSM_DATABASE_STATUS_API_URL,

  OAM_TITILER_ENDPOINT: env.VITE_OAM_TITILER_ENDPOINT,

  OAM_S3_BUCKET_URL: env.VITE_OAM_S3_BUCKET_URL,

  MATOMO_TRACKING_URL: env.VITE_MATOMO_TRACKING_URL,
  BANNER_TIMEOUT_DURATION: env.VITE_BANNER_TIMEOUT_DURATION,
  MAXIMUM_PREDICTION_AREA: env.VITE_MAXIMUM_PREDICTION_AREA,
  MAXIMUM_PREDICTION_TOLERANCE: env.VITE_MAXIMUM_PREDICTION_TOLERANCE,
  FAIR_MODELS_BASE_PATH: env.VITE_FAIR_MODELS_BASE_PATH,
  OFFSET_STEP: env.VITE_OFFSET_STEP,
  MAXIMUM_ORTHO_SKEW_TOLEARANCE_AND_MAX_ANGLE_CHANGE_IN_DEGREES:
    env.VITE_MAXIMUM_ORTHO_SKEW_TOLEARANCE_AND_MAX_ANGLE_CHANGE_IN_DEGREES,

  PREDICTIONS_RESULTS_POINT_FILL_COLOR:
    env.VITE_PREDICTIONS_RESULTS_POINT_FILL_COLOR,
  PREDICTIONS_RESULTS_POINT_OUTLINE_COLOR:
    env.VITE_PREDICTIONS_RESULTS_POINT_OUTLINE_COLOR,

  FAIR_YOUTUBE_UPDATES_URL: env.VITE_FAIR_VIDEO_UPDATES_URL,
  FAIR_VIDEO_BACKUP_URL: env.VITE_FAIR_VIDEO_BACKUP_URL,
  MAPSWIPE_VERIFICATION_NUMBER: env.VITE_MAPSWIPE_VERIFICATION_NUMBER,
  MAPSWIPE_GROUP_SIZE: env.VITE_MAPSWIPE_GROUP_SIZE,
  FAIR_STAC_CATALOG_BASE_URL: env.VITE_FAIR_STAC_CATALOG_BASE_URL,
  NODE_ENV: env.VITE_NODE_ENV,
  TRY_FAIR_GRID_SIZE: env.VITE_TRY_FAIR_GRID_SIZE,
  FAIR_PROD_URL: env.VITE_FAIR_PROD_URL,
};
