/**
 * The environment variables.
 */
export const ENVS = {
  BASE_API_URL: import.meta.env.VITE_BASE_API_URL,

  MATOMO_ID: import.meta.env.VITE_MATOMO_ID,

  MATOMO_APP_DOMAIN: import.meta.env.VITE_MATOMO_APP_DOMAIN,

  KPI_STATS_CACHE_TIME: import.meta.env.VITE_KPI_STATS_CACHE_TIME,

  MAX_TRAINING_AREA_SIZE: import.meta.env.VITE_MAX_TRAINING_AREA_SIZE,

  MIN_TRAINING_AREA_SIZE: import.meta.env.VITE_MIN_TRAINING_AREA_SIZE,

  MAX_TRAINING_AREA_UPLOAD_FILE_SIZE: import.meta.env
    .VITE_MAX_TRAINING_AREA_UPLOAD_FILE_SIZE,

  FAIR_VERSION: import.meta.env.VITE_FAIR_VERSION,

  OSM_HASHTAGS: import.meta.env.VITE_OSM_HASHTAGS,

  MAX_ZOOM_LEVEL: import.meta.env.VITE_MAX_ZOOM_LEVEL,

  MIN_ZOOM_LEVEL_FOR_START_MAPPING_PREDICTION: import.meta.env
    .VITE_MIN_ZOOM_LEVEL_FOR_START_MAPPING_PREDICTION,

  MIN_ZOOM_LEVEL_FOR_TRAINING_AREA_LABELS: import.meta.env
    .VITE_MIN_ZOOM_LEVEL_FOR_TRAINING_AREA_LABELS,

  TRAINING_AREAS_AOI_FILL_COLOR: import.meta.env
    .VITE_TRAINING_AREAS_AOI_FILL_COLOR,

  TRAINING_AREAS_AOI_OUTLINE_COLOR: import.meta.env
    .VITE_TRAINING_AREAS_AOI_OUTLINE_COLOR,

  TRAINING_AREAS_AOI_OUTLINE_WIDTH: import.meta.env
    .VITE_TRAINING_AREAS_AOI_OUTLINE_WIDTH,

  TRAINING_AREAS_AOI_FILL_OPACITY: import.meta.env
    .VITE_TRAINING_AREAS_AOI_FILL_OPACITY,

  TRAINING_AREAS_AOI_LABELS_FILL_OPACITY: import.meta.env
    .VITE_TRAINING_AREAS_AOI_LABELS_FILL_OPACITY,

  TRAINING_AREAS_AOI_LABELS_OUTLINE_WIDTH: import.meta.env
    .VITE_TRAINING_AREAS_AOI_LABELS_OUTLINE_WIDTH,

  TRAINING_AREAS_AOI_LABELS_FILL_COLOR: import.meta.env
    .VITE_TRAINING_AREAS_AOI_LABELS_FILL_COLOR,

  TRAINING_AREAS_MASK_FILL_COLOR: import.meta.env
    .VITE_TRAINING_AREAS_MASK_FILL_COLOR,

  TRAINING_AREAS_AOI_LABELS_OUTLINE_COLOR: import.meta.env
    .VITE_TRAINING_AREAS_AOI_LABELS_OUTLINE_COLOR,

  JOSM_REMOTE_URL: import.meta.env.VITE_JOSM_REMOTE_URL,

  TRAINING_AREA_LABELS_FETCH_POOLING_INTERVAL_MS: import.meta.env
    .VITE_TRAINING_AREA_LABELS_FETCH_POOLING_INTERVAL_MS,

  OSM_LAST_UPDATED_POOLING_INTERVAL_MS: import.meta.env
    .VITE_OSM_LAST_UPDATED_POOLING_INTERVAL_MS,

  MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREA_LABELS: import.meta.env
    .VITE_MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREA_LABELS,

  MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREAS: import.meta.env
    .VITE_MAX_GEOJSON_FILE_UPLOAD_FOR_TRAINING_AREAS,

  MAX_ACCEPTABLE_POLYGON_IN_TRAINING_AREA_GEOJSON_FILE: import.meta.env
    .VITE_MAX_ACCEPTABLE_POLYGON_IN_TRAINING_AREA_GEOJSON_FILE,

  FAIR_PREDICTOR_API_URL: import.meta.env.VITE_FAIR_PREDICTOR_API_URL,

  OSM_DATABASE_STATUS_API_URL: import.meta.env.VITE_OSM_DATABASE_STATUS_API_URL,

  OAM_TITILER_ENDPOINT: import.meta.env.VITE_OAM_TITILER_ENDPOINT,

  OAM_S3_BUCKET_URL: import.meta.env.VITE_OAM_S3_BUCKET_URL,

  MATOMO_TRACKING_URL: import.meta.env.VITE_MATOMO_TRACKING_URL,
  BANNER_TIMEOUT_DURATION: import.meta.env.VITE_BANNER_TIMEOUT_DURATION,
  MAXIMUM_PREDICTION_AREA: import.meta.env.VITE_MAXIMUM_PREDICTION_AREA,
  MAXIMUM_PREDICTION_TOLERANCE: import.meta.env
    .VITE_MAXIMUM_PREDICTION_TOLERANCE,
  FAIR_MODELS_BASE_PATH: import.meta.env.VITE_FAIR_MODELS_BASE_PATH,
  OFFSET_STEP: import.meta.env.VITE_OFFSET_STEP,
};
