# Generated by Django 6.0.4 on 2026-05-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_id', models.CharField(db_index=True, max_length=200)),
                ('anon_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
            options={
                'indexes': [models.Index(fields=['stac_id'], name='stars_star_stac_id_f1d128_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('stac_id', 'user'), name='unique_user_star'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('stac_id', 'anon_key'), name='unique_anon_star')],
            },
        ),
    ]
