# Generated by Django 6.0.4 on 2026-05-05 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='star',
            name='unique_user_star',
        ),
        migrations.RemoveConstraint(
            model_name='star',
            name='unique_anon_star',
        ),
        migrations.RemoveIndex(
            model_name='star',
            name='stars_star_stac_id_f1d128_idx',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='stac_id',
            new_name='target_id',
        ),
        migrations.AddIndex(
            model_name='star',
            index=models.Index(fields=['target_id'], name='stars_star_target__4ee13b_idx'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('target_id', 'user'), name='unique_user_star'),
        ),
        migrations.AddConstraint(
            model_name='star',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('target_id', 'anon_key'), name='unique_anon_star'),
        ),
    ]
