export { default as KPI } from './kpi/kpi'
export { default as WhatIsFAIR } from './about-fair/about-fair'
export { default as TheFAIRProcess } from './fair-process/fair-process'
export { default as FAQs } from './faqs/faqs'
export { default as CoreFeatures } from './core-features/core-features'
export { default as Corevalues } from './core-values/core-values'
export { default as TaglineBanner } from './tagline/tagline'
export { default as CallToAction } from './cta/cta'
