"""
Django settings for aiproject project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.aiproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.aiproject.com/en/3.1/ref/settings/
"""

import logging
import os
from socket import gethostbyname, gethostname
from urllib.parse import urlparse

import dj_database_url
import environ
from corsheaders.defaults import default_headers

env = environ.Env()

# Set the project base directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Security
DEBUG = env("DEBUG", default=False)
if not DEBUG and env("FORCE_DEBUG", default=False):
    raise ValueError("DEBUG=True not allowed in production. Remove FORCE_DEBUG to override.")

if DEBUG:
    SECRET_KEY = env("SECRET_KEY", default="dev-only-insecure-key-change-in-production")
else:
    SECRET_KEY = env("SECRET_KEY")

LOG_PATH = env("LOG_PATH", default=os.path.join(os.getcwd(), "log"))
os.makedirs(LOG_PATH, exist_ok=True)

HOSTNAME = env("HOSTNAME", default="127.0.0.1")

FRONTEND_URL = env("FRONTEND_URL", default="https://fair.hotosm.org")

API_BASE_URL = env("API_BASE_URL", default="https://fair-dev.hotosm.org/api/v1")

EXPORT_TOOL_API_URL = env(
    "EXPORT_TOOL_API_URL",
    default="https://api-prod.raw-data.hotosm.org/v1",
)

if env("GDAL_LIBRARY_PATH", default=False):
    GDAL_LIBRARY_PATH = env("GDAL_LIBRARY_PATH")

OSM_CLIENT_ID = env("OSM_CLIENT_ID")
OSM_CLIENT_SECRET = env("OSM_CLIENT_SECRET")
OSM_URL = env("OSM_URL", default="https://www.openstreetmap.org")
OSM_SCOPE = env("OSM_SCOPE", default="read_prefs")
OSM_LOGIN_REDIRECT_URI = env(
    "OSM_LOGIN_REDIRECT_URI", default="http://127.0.0.1:8000/api/v1/auth/callback/"
)
OSM_SECRET_KEY = env("OSM_SECRET_KEY")


# S3
USE_S3_TO_UPLOAD_MODELS = env("USE_S3_TO_UPLOAD_MODELS", default=False)
BUCKET_NAME = env("BUCKET_NAME", default="fair-dev")
PARENT_BUCKET_FOLDER = env(
    "PARENT_BUCKET_FOLDER", default="dev"
)  # use prod for production
AWS_REGION = env("AWS_REGION", default="us-east-1")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default=None)
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default=None)
PRESIGNED_URL_EXPIRY = env("PRESIGNED_URL_EXPIRY", default=3600)


# Limiter
EPOCHS_LIMIT = env("EPOCHS_LIMIT", default=20)  ## TODO : Remove this global variable
BATCH_SIZE_LIMIT = env("BATCH_SIZE_LIMIT", default=8)

## YOLO
YOLO_EPOCHS_LIMIT = env("YOLO_EPOCHS_LIMIT", default=200)
YOLO_BATCH_SIZE_LIMIT = env("YOLO_BATCH_SIZE_LIMIT", default=8)

## RAMP
RAMP_EPOCHS_LIMIT = env("RAMP_EPOCHS_LIMIT", default=40)
RAMP_BATCH_SIZE_LIMIT = env("RAMP_BATCH_SIZE_LIMIT", default=8)

TRAINING_WORKSPACE_DOWNLOAD_LIMIT = env(
    "TRAINING_WORKSPACE_DOWNLOAD_LIMIT", default=200
)

## FGB Stream API Safety Limits
# Examples: 500km = ~4.5° at equator, 10000km² = ~100x100km area
FGB_MAX_BBOX_AREA_KM2 = env("FGB_MAX_BBOX_AREA_KM2", default=10000.0)
FGB_MAX_BBOX_DIMENSION_KM = env("FGB_MAX_BBOX_DIMENSION_KM", default=500.0)
FGB_MAX_FEATURES_LIMIT = env("FGB_MAX_FEATURES_LIMIT", default=50000)
FGB_REQUEST_TIMEOUT = env("FGB_REQUEST_TIMEOUT", default=60)
FGB_USE_ARROW_FOR_STREAMING = env("FGB_USE_ARROW_FOR_STREAMING", default=True)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "django.contrib.gis",
    "leaflet",
    "rest_framework",
    "rest_framework_gis",
    "django_filters",
    "corsheaders",
    "login",
    "drf_yasg",
    "celery",
    "django_celery_results",
    "django_q",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", default="").split(",") if not DEBUG else []

DEFAULT_PAGINATION_SIZE = env("DEFAULT_PAGINATION_SIZE", default=50)

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "login.authentication.OsmAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": DEFAULT_PAGINATION_SIZE,
}

ROOT_URLCONF = "aiproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                "staticfiles": "django.templatetags.static",
            },
        },
    },
]

WSGI_APPLICATION = "aiproject.wsgi.application"


# Database
# https://docs.aiproject.com/en/3.1/ref/settings/#databases


DATABASES = {}

DATABASES["default"] = dj_database_url.config(
    default="postgis://admin:password@localhost:5432/fair", 
    conn_max_age=500,
    conn_health_checks=True,
)

if not DEBUG:
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "require",
        **DATABASES["default"].get("OPTIONS", {})
    }

# Password validation
# https://docs.aiproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.aiproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.aiproject.com/en/3.1/howto/static-files/

STATIC_URL = "/api_static/"
MEDIA_URL = "/media/"
STATIC_ROOT = os.path.join(BASE_DIR, "api_static")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

if not DEBUG:
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': os.path.join(LOG_PATH, 'django.log'),
        'formatter': 'verbose',
    }
    LOGGING['handlers']['mail_admins'] = {
        'level': 'ERROR',
        'class': 'django.utils.log.AdminEmailHandler',
    }
    LOGGING['loggers']['django']['handlers'].append('file')
    LOGGING['loggers']['django']['handlers'].append('mail_admins')
    LOGGING['loggers']['core']['handlers'].append('file')

if DEBUG:
    logging.info("Enabling oauthlib insecure transport in debug mode")
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

# celery configuration

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0"
)  # if you don't want to use redis pass 'django-db' to use app db itself

Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 4,
    "retry": 60 * 6,
    "max_retires": 1,
    "recycle": 50,
    "queue_limit": 50,
    "timeout": 60 * 5,  # number of seconds
    "label": "Django Q",
    "orm": "default",
}


AUTH_USER_MODEL = "login.OsmUser"

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "OSM": {"type": "apiKey", "name": "access-token", "in": "header"},
    }
}
# get ramp home and set it to environ
RAMP_HOME = env("RAMP_HOME", default=None)
if RAMP_HOME:
    os.environ["RAMP_HOME"] = RAMP_HOME
YOLO_HOME = env("YOLO_HOME", default=os.getcwd())


# training workspace
TRAINING_WORKSPACE = env(
    "TRAINING_WORKSPACE", default=os.path.join(os.getcwd(), "training")
)
PREDICTION_WORKSPACE = env(
    "PREDICTION_WORKSPACE", default=os.path.join(os.getcwd(), "prediction")
)

LOG_LINE_STREAM_TRUNCATE_VALUE = env("LOG_LINE_STREAM_TRUNCATE_VALUE", default=10)


TEST_RUNNER = "tests.test_runners.NoDestroyTestRunner"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "example-email@example.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "example-email-password")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")
FAIL_EMAIL_SILENTLY = os.getenv("FAIL_EMAIL_SILENTLY", "True")

# CORS settings


CACHE_TIMEOUT_MINUTES = int(os.getenv("CACHE_TIMEOUT_MINUTES", 5))

RATELIMIT_ENABLE = not DEBUG
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'core.ratelimit.ratelimit_key_from_user'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

TRAINING_RATE_LIMIT = env("TRAINING_RATE_LIMIT", default="10/h")
PREDICTION_RATE_LIMIT = env("PREDICTION_RATE_LIMIT", default="50/h")
API_RATE_LIMIT = env("API_RATE_LIMIT", default="1000/h")


def extract_domain(url):
    return urlparse(url).hostname

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = False
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOW_CREDENTIALS = True
    cors_origins = env("CORS_ALLOWED_ORIGINS", default="").split(",")
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins if origin.strip()]
    if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOW_HEADERS = list(default_headers) + [
    "access-token",
    "authorization", 
    "content-type",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOWED_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']
CORS_PREFLIGHT_MAX_AGE = 86400
base_allowed_hosts = [
    "localhost",
    "127.0.0.1", 
    env("HOSTNAME", default="127.0.0.1"),
]

if not DEBUG:
    production_hosts = env("ALLOWED_HOSTS", default="").split(",")
    base_allowed_hosts.extend([host.strip() for host in production_hosts if host.strip()])
    if FRONTEND_URL:
        frontend_domain = extract_domain(FRONTEND_URL)
        if frontend_domain and frontend_domain not in base_allowed_hosts:
            base_allowed_hosts.append(frontend_domain)
else:
    try:
        base_allowed_hosts.extend([gethostname(), gethostbyname(gethostname())])
    except Exception:
        pass

if 'CORS_ALLOWED_ORIGINS' in locals():
    base_allowed_hosts.extend([extract_domain(url) for url in CORS_ALLOWED_ORIGINS if url and extract_domain(url)])

ALLOWED_HOSTS = list(set(filter(None, base_allowed_hosts)))

# Security validation for production
if not DEBUG:
    required_env_vars = [
        'SECRET_KEY', 'DATABASE_URL', 'ALLOWED_HOSTS', 
        'OSM_CLIENT_ID', 'OSM_CLIENT_SECRET', 'OSM_SECRET_KEY'
    ]
    missing_vars = [var for var in required_env_vars if not env(var, default=None)]
    if missing_vars:
        raise ValueError(f"Required environment variables missing in production: {', '.join(missing_vars)}")
    
    if 'dev' in SECRET_KEY or 'default' in SECRET_KEY or len(SECRET_KEY) < 32:
        raise ValueError("Insecure SECRET_KEY detected in production")
