# Generated by Django 4.1.4 on 2024-05-30 15:20

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('label_status', models.IntegerField(choices=[(1, 'Downloaded'), (-1, 'Not Downloaded'), (0, 'Running')], default=-1)),
                ('label_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_imagery', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Archived'), (0, 'Active'), (-1, 'Draft')], default=-1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('label_status', models.IntegerField(choices=[(1, 'Downloaded'), (-1, 'Not Downloaded'), (0, 'Running')], default=-1)),
                ('label_fetched', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('source_imagery', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('published_training', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Archived'), (0, 'Published'), (-1, 'Draft')], default=-1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_imagery', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoom_level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=4)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('epochs', models.PositiveIntegerField()),
                ('chips_length', models.PositiveIntegerField(default=0)),
                ('batch_size', models.PositiveIntegerField()),
                ('freeze_layers', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aoi')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedbackaoi')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackaoi',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.training'),
        ),
        migrations.AddField(
            model_name='feedbackaoi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zoom_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(23)])),
                ('feedback_type', models.CharField(choices=[('TP', 'True Positive'), ('TN', 'True Negative'), ('FP', 'False Positive'), ('FN', 'False Negative')], max_length=10)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
                ('source_imagery', models.URLField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
        ),
        migrations.AddField(
            model_name='aoi',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset'),
        ),
    ]
