# Generated by Django 4.1.4 on 2024-05-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='chips_length',
        ),
    ]
