# Generated by Django 4.1.4 on 2024-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_training_chips_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='chips_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
