# Generated by Django 4.1.4 on 2025-01-02 20:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_approvedpredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='approvedpredictions',
            old_name='approved_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='aoi',
            name='user',
            field=models.ForeignKey(default=7004124, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='base_model',
            field=models.CharField(choices=[('RAMP', 'RAMP'), ('YOLO_V8_V1', 'YOLO_V8_V1'), ('YOLO_V8_V2', 'YOLO_V8_V2')], default='RAMP', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
