# Generated by Django 5.2.1 on 2025-07-07 19:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_dataset_offset_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='source_imagery',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='zoom_level',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='training',
        ),
        migrations.AddField(
            model_name='feedback',
            name='action',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='ACCEPT', max_length=6),
        ),
        migrations.AddField(
            model_name='feedback',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.training'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mapswipe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
        ),
    ]
