# Generated by Django 5.2.1 on 2025-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prediction_result_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='base_model',
            field=models.CharField(choices=[('RAMP', 'RAMP'), ('YOLO_V8_V1', 'YOLO_V8_V1'), ('YOLO_V8_V2', 'YOLO_V8_V2'), ('YOLO_V11', 'YOLO_V11'), ('YOLO_V11_SAM', 'YOLO_V11_SAM')], default='RAMP', max_length=50),
        ),
    ]
