name: Build Docker Images for backend

on:
  push:
    branches:
      - master
      - develop

    paths:
      - "backend/**"
      - ".github/workflows/docker_build.yml"
  pull_request:
    branches:
      - master
      - develop

    paths:
      - "backend/**"
      - ".github/workflows/docker_build.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-api-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API Docker
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/Dockerfile_CPU
          push: false
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

  build-and-push-worker-image:
    needs: build-and-push-api-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Worker Docker
        id: meta_worker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}_worker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Worker Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend/
          file: backend/Dockerfile
          push: false
          tags: ${{ steps.meta_worker.outputs.tags }}
          labels: ${{ steps.meta_worker.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
