name: Frontend Build

on:
  push:
    branches: [master, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_build.yml"
  pull_request:
    branches: [master, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_build.yml"

jobs:
  Build_On_Ubuntu:
    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node.js dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: npm install

      - name: Build
        working-directory: ./frontend
        run: npm run build
