name: Frontend Build

on:
  push:
    branches: [master, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_build.yml"
  pull_request:
    branches: [master, develop]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_build.yml"

jobs:
  Build_On_Ubuntu:
    runs-on: ubuntu-latest
    env:
      CI: false

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd frontend/
          npm install

      - name: Build
        run: |
          cd frontend/
          npm run build
