name: Frontend Build and upload to S3

on:
  release:
    types: [released]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_build_push.yml"
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    environment: Production
    env:
      CI: false

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd frontend/ && npm install

      - name: Build frontend
        run: cd frontend/ && npm run build
        env:
          VITE_BASE_API_URL: ${{ vars.VITE_BASE_API_URL }}
          VITE_PREDICTOR_BASE_API_URL: ${{ vars.VITE_PREDICTOR_BASE_API_URL }}
          VITE_MATOMO_ID: ${{ vars.VITE_MATOMO_ID }}
          VITE_MATOMO_APP_DOMAIN: ${{ vars.VITE_MATOMO_APP_DOMAIN }}
          
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: fAIrGithub

      - name: Upload to S3
        run: cd frontend/dist && aws s3 sync . s3://${{ vars.FRONTEND_BUCKET }}/
