name: 🧪 PR Tests Frontend

on:
  pull_request:
    branches:
      - develop
      - master
    # Workflow is triggered only if src/frontend changes
    paths:
      - src/frontend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  unit-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@3.2.0
    with:
      working_dir: src/frontend