name: Build ZenML Postgres Image

on:
  workflow_dispatch:
    inputs:
      zenml_version:
        description: "ZenML version to build"
        required: true
        type: string

jobs:
  server-image:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.6.0
    with:
      context: infra/zenml
      # This remains hotosm/zenml-postgres for legacy reasons
      # Ideally it would be hotosm/fair/zenml-postgres
      image_name: ghcr.io/${{ github.repository_owner }}/zenml-postgres
      build_target: runtime
      dockerfile: infra/zenml/Dockerfile.postgres
      extra_build_args: ZENML_VERSION=${{ inputs.zenml_version }}
      image_tags: ${{ inputs.zenml_version }}

  cli-image:
    needs: server-image
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.6.0
    with:
      context: infra/zenml
      image_name: ghcr.io/${{ github.repository }}/cli
      build_target: cli
      dockerfile: infra/zenml/Dockerfile.cli
      extra_build_args: ZENML_VERSION=${{ inputs.zenml_version }}
      image_tags: ${{ inputs.zenml_version }}
