# Generated by Django 6.0.4 on 2026-05-04 15:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_id', models.CharField(db_index=True, max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], default='accept', max_length=6)),
                ('comments', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, to_field='osm_id')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stac_id'], name='feedback_fe_stac_id_f90a19_idx'), models.Index(fields=['user'], name='feedback_fe_user_id_b3b486_idx'), models.Index(fields=['action'], name='feedback_fe_action_d3e6dc_idx'), models.Index(fields=['geom'], name='feedback_geom_gist_idx', opclasses=['gist'])],
            },
        ),
    ]
